// Generated by Selenium IDE
package firstpckg;
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class ComplicatedsearchTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void complicatedsearch() {
    driver.get("https://www.google.com/search?q=cricket&sca_esv=571184275&sxsrf=AM9HkKl3nAO5qMZDoxVCTijXZrqMrNUg1g%3A1696568105655&source=hp&ei=KZMfZbmDJsDs2roPgsu_IA&iflsig=AO6bgOgAAAAAZR-hORZI12fKgJ3QQ1g-v07nztX4PFgj&ved=0ahUKEwj5u5fa0OCBAxVAtlYBHYLlDwQQ4dUDCAo&uact=5&oq=cricket&gs_lp=Egdnd3Mtd2l6Igdjcmlja2V0MgcQIxiKBRgnMgsQLhiABBixAxiDATIOEAAYigUYsQMYgwEYkQIyDhAAGIoFGLEDGIMBGJECMgsQABiABBixAxiDATIOEAAYigUYsQMYgwEYkQIyCxAAGIAEGLEDGIMBMgsQABiKBRixAxiDATILEAAYgAQYsQMYgwEyCxAAGIAEGLEDGIMBSPASUABYqQ1wAHgAkAEAmAGeAaABwAaqAQMwLje4AQPIAQD4AQHCAgcQLhiKBRgnwgINEAAYigUYsQMYgwEYQ8ICCxAuGIoFGLEDGIMBwgINEC4YigUYxwEY0QMYQ8ICEBAAGIAEGBQYhwIYsQMYgwHCAg0QLhiKBRixAxiDARhDwgIIEC4YgAQYsQM&sclient=gws-wiz");
    driver.manage().window().setSize(new Dimension(814, 816));
    driver.findElement(By.cssSelector(".LatpMc:nth-child(1) .FMKtTb")).click();
    driver.close();
  }
}
