// Generated by Selenium IDE
package firstpckg;
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class DemoTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void demo() {
    driver.get("https://www.google.com/search?q=crick&sca_esv=571184275&sxsrf=AM9HkKmWx8-b0DCHhyDeJNpEWeKEw5OAGw%3A1696568995182&source=hp&ei=o5YfZfrnCI-ohwOfypPoBg&iflsig=AO6bgOgAAAAAZR-ks2v32JKJwLQ2qiR3br2a8WISnKmp&ved=0ahUKEwi6xauC1OCBAxUP1GEKHR_lBG0Q4dUDCAo&uact=5&oq=crick&gs_lp=Egdnd3Mtd2l6IgVjcmljazIHECMYigUYJzILEC4YgAQYsQMYgwEyDhAAGIoFGLEDGIMBGJECMgcQABiKBRhDMgsQABiABBixAxiDATINEAAYigUYsQMYgwEYQzILEAAYgAQYsQMYgwEyBxAuGIoFGEMyBxAuGIoFGEMyCxAAGIoFGLEDGIMBSI0uUABYzwZwAHgAkAEAmAGiAaABlwWqAQMwLjW4AQPIAQD4AQHCAgcQLhiKBRgnwgILEC4YigUYsQMYgwHCAggQABiABBixA8ICBRAAGIAEwgIQEAAYgAQYFBiHAhixAxiDAcICCBAAGIoFGJECwgIIEC4YgAQYsQM&sclient=gws-wiz");
    driver.manage().window().setSize(new Dimension(814, 816));
    {
      WebElement element = driver.findElement(By.cssSelector(".nPDzT:nth-child(4) .FMKtTb"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.findElement(By.id("APjFqb")).click();
    driver.findElement(By.cssSelector(".WggQGd > span")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".LatpMc:nth-child(4) > .GKS7s"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    {
      WebElement element = driver.findElement(By.cssSelector("#uJYfZcuYAcuv4-EP8Oy6qAM__7 .GKS7s"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    {
      WebElement element = driver.findElement(By.cssSelector("#uJYfZcuYAcuv4-EP8Oy6qAM__7 .FMKtTb"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.cssSelector(".LatpMc:nth-child(2) .FMKtTb")).click();
    {
      WebElement element = driver.findElement(By.linkText("All"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
  }
}
